FROM node:7.6.0-alpine
MAINTAINER Michael Chambers <magic.code.interactive@gmail.com>

WORKDIR /usr/app/
COPY server/installation.js  /usr/app/
COPY src/package.json /usr/app/

# If you have native dependencies, you'll need extra tools
# RUN apk add --no-cache make gcc g++ python

# If you need npm, don't use a base tag
RUN cd /usr/app/ && npm install

EXPOSE 55555
CMD ["node", "/usr/app/pub.js"]
# Make volume path
VOLUME ["/usr/app/.env", "/usr/app/Schema"]

# Start server (Can't start yet bacause volume is not ready yet, we'll start with compose instead)
# CMD [ "npm", "start"]